### ISSUE TITLE
Why do the color looks so weird

### ISSUE THREAD

**Issue by FlashDragons** [BelmuTM/NobleRT#10]
Shader ver.: NobleRT v.1.4.1
Shader loader: iris-mc1.20-1.6.4
Issue: I feel that the color is blue and green, and there are many small black dots in the game screen.
![2023-08-01_15 49 57](https://github.com/BelmuTM/NobleRT/assets/132655963/89082834-aa6b-4e42-a0b2-b3633a202164)
![2023-08-01_15 50 05](https://github.com/BelmuTM/NobleRT/assets/132655963/132557ba-c8ae-41f2-93e8-86ebccf7efad)
![2023-08-01_11 52 20](https://github.com/BelmuTM/NobleRT/assets/132655963/be8f91b0-33f7-4509-83ff-99f671bd55d3)
![2023-08-01_15 49 36](https://github.com/BelmuTM/NobleRT/assets/132655963/67d95b34-f025-4361-9b31-8d38f2ed4ce1)

**Comment by FlashDragons** [comment]
I didn't change any settings.

**Comment by FlashDragons** [comment]
I found the problem, [chunksfadein](https://github.com/kerudion/chunksfadein) is not compatible, but it's okay, this mod is a beta version. And I will post an issue for that mod later.
There is another problem, when this shader works with [Neat](https://github.com/VazkiiMods/Neat), the creatures' health bars will have small dots. Also, some items may have small spots on the surface, such as the door and dog in the picture.
![2023-08-02_00 26 36](https://github.com/BelmuTM/NobleRT/assets/132655963/28a96205-65c4-4bb1-8887-e7c5c1875d5f)
Looking forward to the next version of this shader!

**Comment by BelmuTM** [comment]
I don't provide support for mod-related problems, it is not Noble's job to support the mods, but it is the mods' job to support Noble. Thanks for reporting your issue anyways.
