### ISSUE TITLE
not working with sodium

### ISSUE THREAD

**Issue by tntisthebomb** [BelmuTM/NobleRT#4]
is there a way to get this to work with sodium?

**Comment by BelmuTM** [comment]
Hi, Sodium needs to support Noble, it shouldn't be the other way. Simply because mods like Sodium have a purpose of making the shaderpack's code work. You can either wait for it to support a larger amount of shaderpacks or use Optifine in the mean time.

**Comment by itsdinkd** [comment]
You can't expect a major mod to go out of there way to support a minor shader pack...
