### ISSUE TITLE
very bright light (bug)

### ISSUE THREAD

**Issue by mirususamongus** [BelmuTM/NobleRT#7]
Shader ver.: NobleRT v.1.3.3
Shader loader: iris mc1.19.4-1.6.3
Issue: when entering or leaving buildings and when being outside in general, the light at default settings is too bright
![2023-06-05_03 30 07](https://github.com/BelmuTM/NobleRT/assets/80936529/5eea324f-49d3-45a2-9c6a-dec35aa8fa59)
![2023-06-05_03 30 18](https://github.com/BelmuTM/NobleRT/assets/80936529/6f4197ae-129b-4833-a72f-232f223d8aa2)

**Comment by BelmuTM** [comment]
Hi, this is not a bug, this is the Automatic Exposure. It is meant to simulate how your eyes adapt to dark / bright environments over time.
