### ISSUE TITLE
max 30 fps at default settings

### ISSUE THREAD

**Issue by mirususamongus** [BelmuTM/NobleRT#8]
Shader ver.: NobleRT v.1.3.3
Shader loader: iris mc1.19.4-1.6.3
Issue: when the character does not move at a maximum fps of 30, when moving, lags immediately appear with a drop in fps to 15. if we take the Seuss ptgi hrr\e12 shaders as a comparison, then it gives 60 fps stably. even when lowering the settings, the fps practically does not move from 30
![2023-06-05_03 29 49](https://github.com/BelmuTM/NobleRT/assets/80936529/c166909a-14d6-4244-ad8a-d0b6a4dde142)

**Comment by BelmuTM** [comment]
Hi, SEUS PTGI and NobleRT are 2 very different shaderpacks, therefore you can't expect them to run the same way. However, I do recognize NobleRT needs some optimization, which will be done in the future.
