### ISSUE TITLE
I am getting this error: deferred3.fsh: deferred3.fsh: 0(484) : error C1503: undefined variable "atmosphereRayPosition"

### ISSUE THREAD

**Issue by Ender436** [BelmuTM/NobleRT#9]
I ran the shaders for the first time in 1.20.1, and they worked fine, I went into the settings to do some tweaking, and after making changes, when I tried to apply them, the shaders failed to load. I then tried tweaking the settings to see what was the problem, and they still won't load. I have tried changing the settings to the different presets, but they still won't load. I've also tried reloading the game, and they still fail to load, and give me the same error.

**Comment by BelmuTM** [comment]
Hi, what are the settings you changed please ?

**Comment by Ender436** [comment]
I kind of changed a lot, but I'll list the ones I remember changing for sure:
turned on GI
turned on water caustics
turned down a few samples, for clouds specifically and maybe some other things as well
turned up the shutter speed
turned on cloud shadows

and actually it would appear that turning off the cloud shadows may have fixed it, the shaders just loaded.

**Comment by BelmuTM** [comment]
Ah yeah, clouds shadows are broken and I need to fix them. It will be fixed in the next release, thanks for reporting the issue! Have a nice one.

**Comment by Ender436** [comment]
Thanks, you too!
